server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter
        - id: account-service
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/account/**
          filters:
            - AuthFilter

